# Hello World Neural Network

In [2]:
import numpy as np
import pandas as pd
import PIL as pillow
import matplotlib.pyplot as plt
%matplotlib inline
import os

## Preprocess the MNIST Dataset for the Neural Network

In [25]:
train_data = pd.read_csv("dataset/train_dataset.csv")
test_data = pd.read_csv("dataset/test_dataset.csv")

train_labels = []
test_labels = []
input_list = []
target_list = []
test_list = []

def show_num(img_array):
    img = img_array.reshape((28,28))
    plt.imshow(img, cmap='Greys', interpolation=None)

# Split train data in Targets, Labels and Inputs for the NN
for i in range(len(train_data)):
    label = train_data.iloc[i][0]
    target = np.zeros(10) + 0.01
    target[label] = 0.99
    target_list.append(target)
    train_labels.append(label)
    input_list.append(train_data.iloc[i][1:])

# Split test data in Tests
for i in range(len(test_data)):
    test_list.append(test_data.iloc[i][1:])
    test_labels.append(test_data.iloc[i][0])

# Normalize the input data in range [0, 1] for the NN
inputs = (np.asfarray(input_list)/255.0 * 0.99) + 0.01
targets = (np.asfarray(target_list))
tests = (np.asfarray(test_list)/255.0 * 0.99) + 0.01

## Implementation of the NN

In [38]:
def sigmoid(x, deriv=False):
    if deriv:
        return x * (1 - x)
    return 1/(1 + np.e**-x)

IN_NEURONS = 784
HIDD_NEURONS = 2
OUT_NEURONS = 10
LEARNING_RATE = 0.3
EPOCHS = 100

W_in_hidd = (2*np.random.rand(HIDD_NEURONS, IN_NEURONS) - 1)*0.99
W_hidd_out = (2*np.random.rand(OUT_NEURONS, HIDD_NEURONS) - 1)*0.99

for e in range(EPOCHS):
    for i in range(len(inputs)):
        I = np.array(inputs[i], ndmin=2).T
        T = np.array(targets[i], ndmin=2).T
        in_layer = I
        hidd_layer = sigmoid(W_in_hidd.dot(I))
        out_layer = sigmoid(W_hidd_out.dot(hidd_layer))

        error_out = T - out_layer
        error_hidden = W_hidd_out.T.dot(error_out)
        error_input = W_in_hidd.T.dot(error_hidden)

        out_layer_delta = error_out * sigmoid(out_layer, deriv=True)
        W_hidd_out += LEARNING_RATE * out_layer_delta.dot(hidd_layer.T)
        hidd_layer_delta = error_hidden * sigmoid(hidd_layer, deriv=True)
        W_in_hidd += LEARNING_RATE * hidd_layer_delta.dot(in_layer.T)

for i in range(len(tests)):
    I = np.array(tests[i], ndmin=2).T
    in_layer = I
    hidd_layer = sigmoid(W_in_hidd.dot(I))
    out_layer = sigmoid(W_hidd_out.dot(hidd_layer))
    print("Output:")
    print(test_labels[i])
    print(out_layer)
    print(np.argmax(out_layer))

Output:
4
[[0.03921474]
 [0.07675227]
 [0.07429844]
 [0.10002302]
 [0.09030383]
 [0.07681162]
 [0.07999537]
 [0.4787999 ]
 [0.08525206]
 [0.08186135]]
7
Output:
7
[[0.04528571]
 [0.08621652]
 [0.08626596]
 [0.20655697]
 [0.07578981]
 [0.08766636]
 [0.08490275]
 [0.36502866]
 [0.0813967 ]
 [0.08479194]]
7
Output:
8
[[0.05753737]
 [0.10450407]
 [0.11032676]
 [0.5210948 ]
 [0.05613888]
 [0.10903836]
 [0.09375534]
 [0.20729056]
 [0.07526528]
 [0.08992056]]
3
