# Hello World Neural Network

In [2]:
import numpy as np
import pandas as pd
import PIL as pillow
import matplotlib.pyplot as plt
%matplotlib inline
import os

## Preprocess the MNIST Dataset for the Neural Network

In [3]:
train_data = pd.read_csv("dataset/mnist_train_100.csv")
test_data = pd.read_csv("dataset/mnist_test_10.csv")

train_labels = []
test_labels = []
input_list = []
target_list = []
test_list = []

def show_num(img_array):
    img = img_array.reshape((28,28))
    plt.imshow(img, cmap='Greys', interpolation=None)

# Split train data in Targets, Labels and Inputs for the NN
for i in range(len(train_data)):
    label = train_data.iloc[i][0]
    target = np.zeros(10) + 0.01
    target[label] = 0.99
    target_list.append(target)
    train_labels.append(label)
    input_list.append(train_data.iloc[i][1:])

# Split test data in Tests
for i in range(len(test_data)):
    test_list.append(test_data.iloc[i][1:])
    test_labels.append(test_data.iloc[i][0])

# Normalize the input data in range [0, 1] for the NN
inputs = (np.asfarray(input_list)/255.0 * 0.99) + 0.01
targets = (np.asfarray(target_list))
tests = (np.asfarray(test_list)/255.0 * 0.99) + 0.01

## Implementation of the NN
### Best Result:
Learning Rate = 0.3

Input Neurons = 784

Hidden Neurons = 100

Ouput Neurons = 10

Mean score of the NN is 66.66666666666666 per test in per cent.

In [32]:
def sigmoid(x, deriv=False):
    if deriv:
        return x * (1 - x)
    return 1/(1 + np.e**-x)

IN_NEURONS = 784
HIDD_NEURONS = 100
OUT_NEURONS = 10
LEARNING_RATE = 0.3
EPOCHS = 10
LEN_TEST_DATA = len(tests)

W_in_hidd = np.random.normal(0.0, pow(HIDD_NEURONS, -1/2), (HIDD_NEURONS, IN_NEURONS))
W_hidd_out = np.random.normal(0.0, pow(OUT_NEURONS, -1/2), (OUT_NEURONS, HIDD_NEURONS))

score = 0
score_list = []

for e in range(EPOCHS):
    for i in range(len(inputs)):
        I = np.array(inputs[i], ndmin=2).T
        T = np.array(targets[i], ndmin=2).T
        in_layer = I
        hidd_layer = sigmoid(W_in_hidd.dot(I))
        out_layer = sigmoid(W_hidd_out.dot(hidd_layer))

        error_out = T - out_layer
        error_hidden = W_hidd_out.T.dot(error_out)
        error_input = W_in_hidd.T.dot(error_hidden)

        out_layer_delta = error_out * sigmoid(out_layer, deriv=True)
        W_hidd_out += LEARNING_RATE * out_layer_delta.dot(hidd_layer.T)
        hidd_layer_delta = error_hidden * sigmoid(hidd_layer, deriv=True)
        W_in_hidd += LEARNING_RATE * hidd_layer_delta.dot(in_layer.T)

for _ in range(100):
    for i in range(LEN_TEST_DATA):
        I = np.array(tests[i], ndmin=2).T
        in_layer = I
        hidd_layer = sigmoid(W_in_hidd.dot(I))
        out_layer = sigmoid(W_hidd_out.dot(hidd_layer))
        answer = np.argmax(out_layer)
        label = test_labels[i]
        print("Output:")
        print(out_layer)
        print("Label {}".format(label))
        print("Answer of the NN is {}.".format(answer))
        if answer == label:
            score += 1
    print("Statistics of the NN:")
    print("Score: {} of {} correct.".format(score, LEN_TEST_DATA))
    score_list.append(score)
    score = 0
sum_score = sum(score_list)
mean_score = sum_score/(100*LEN_TEST_DATA)
print("Mean score of the NN is {} per test in per cent.".format(mean_score*100))

Output:
[[0.43963714]
 [0.00854484]
 [0.45763481]
 [0.02109729]
 [0.00076583]
 [0.10380043]
 [0.06715647]
 [0.00459864]
 [0.02720487]
 [0.00190836]]
Label 2
Answer of the NN is 2.
Output:
[[0.00731108]
 [0.98018983]
 [0.02762158]
 [0.01459108]
 [0.0093039 ]
 [0.02486301]
 [0.01641603]
 [0.00965292]
 [0.00726756]
 [0.02505962]]
Label 1
Answer of the NN is 1.
Output:
[[0.81885463]
 [0.00664031]
 [0.01765856]
 [0.00297947]
 [0.00388589]
 [0.00546423]
 [0.05624452]
 [0.0681655 ]
 [0.00451161]
 [0.00288135]]
Label 0
Answer of the NN is 0.
Output:
[[0.01259507]
 [0.0027706 ]
 [0.03732517]
 [0.00506555]
 [0.9348983 ]
 [0.00930126]
 [0.01623883]
 [0.12060654]
 [0.0186705 ]
 [0.02493413]]
Label 4
Answer of the NN is 4.
Output:
[[0.00688828]
 [0.98254642]
 [0.01787129]
 [0.01396862]
 [0.00823656]
 [0.0152356 ]
 [0.00534242]
 [0.014027  ]
 [0.00734004]
 [0.0177523 ]]
Label 1
Answer of the NN is 1.
Output:
[[0.00078025]
 [0.00244279]
 [0.00730579]
 [0.01343052]
 [0.34328002]
 [0.02831128]
 [0.0310

Output:
[[0.04499681]
 [0.37464897]
 [0.01091519]
 [0.00109536]
 [0.26292005]
 [0.00743711]
 [0.09651495]
 [0.00350992]
 [0.01114994]
 [0.00052363]]
Label 5
Answer of the NN is 1.
Output:
[[0.00753632]
 [0.00461438]
 [0.00357422]
 [0.00221661]
 [0.12989398]
 [0.00518615]
 [0.02295351]
 [0.09032299]
 [0.004426  ]
 [0.20623339]]
Label 9
Answer of the NN is 9.
Statistics of the NN:
Score: 6 of 9 correct.
Output:
[[0.43963714]
 [0.00854484]
 [0.45763481]
 [0.02109729]
 [0.00076583]
 [0.10380043]
 [0.06715647]
 [0.00459864]
 [0.02720487]
 [0.00190836]]
Label 2
Answer of the NN is 2.
Output:
[[0.00731108]
 [0.98018983]
 [0.02762158]
 [0.01459108]
 [0.0093039 ]
 [0.02486301]
 [0.01641603]
 [0.00965292]
 [0.00726756]
 [0.02505962]]
Label 1
Answer of the NN is 1.
Output:
[[0.81885463]
 [0.00664031]
 [0.01765856]
 [0.00297947]
 [0.00388589]
 [0.00546423]
 [0.05624452]
 [0.0681655 ]
 [0.00451161]
 [0.00288135]]
Label 0
Answer of the NN is 0.
Output:
[[0.01259507]
 [0.0027706 ]
 [0.03732517]
 [0.0

Output:
[[0.00078025]
 [0.00244279]
 [0.00730579]
 [0.01343052]
 [0.34328002]
 [0.02831128]
 [0.03101971]
 [0.02936238]
 [0.02496415]
 [0.72077414]]
Label 4
Answer of the NN is 9.
Output:
[[0.00203896]
 [0.01030875]
 [0.00716818]
 [0.29977511]
 [0.27293757]
 [0.00854992]
 [0.03784217]
 [0.00947253]
 [0.00522758]
 [0.01406943]]
Label 9
Answer of the NN is 3.
Output:
[[0.04499681]
 [0.37464897]
 [0.01091519]
 [0.00109536]
 [0.26292005]
 [0.00743711]
 [0.09651495]
 [0.00350992]
 [0.01114994]
 [0.00052363]]
Label 5
Answer of the NN is 1.
Output:
[[0.00753632]
 [0.00461438]
 [0.00357422]
 [0.00221661]
 [0.12989398]
 [0.00518615]
 [0.02295351]
 [0.09032299]
 [0.004426  ]
 [0.20623339]]
Label 9
Answer of the NN is 9.
Statistics of the NN:
Score: 6 of 9 correct.
Output:
[[0.43963714]
 [0.00854484]
 [0.45763481]
 [0.02109729]
 [0.00076583]
 [0.10380043]
 [0.06715647]
 [0.00459864]
 [0.02720487]
 [0.00190836]]
Label 2
Answer of the NN is 2.
Output:
[[0.00731108]
 [0.98018983]
 [0.02762158]
 [0.0

Output:
[[0.81885463]
 [0.00664031]
 [0.01765856]
 [0.00297947]
 [0.00388589]
 [0.00546423]
 [0.05624452]
 [0.0681655 ]
 [0.00451161]
 [0.00288135]]
Label 0
Answer of the NN is 0.
Output:
[[0.01259507]
 [0.0027706 ]
 [0.03732517]
 [0.00506555]
 [0.9348983 ]
 [0.00930126]
 [0.01623883]
 [0.12060654]
 [0.0186705 ]
 [0.02493413]]
Label 4
Answer of the NN is 4.
Output:
[[0.00688828]
 [0.98254642]
 [0.01787129]
 [0.01396862]
 [0.00823656]
 [0.0152356 ]
 [0.00534242]
 [0.014027  ]
 [0.00734004]
 [0.0177523 ]]
Label 1
Answer of the NN is 1.
Output:
[[0.00078025]
 [0.00244279]
 [0.00730579]
 [0.01343052]
 [0.34328002]
 [0.02831128]
 [0.03101971]
 [0.02936238]
 [0.02496415]
 [0.72077414]]
Label 4
Answer of the NN is 9.
Output:
[[0.00203896]
 [0.01030875]
 [0.00716818]
 [0.29977511]
 [0.27293757]
 [0.00854992]
 [0.03784217]
 [0.00947253]
 [0.00522758]
 [0.01406943]]
Label 9
Answer of the NN is 3.
Output:
[[0.04499681]
 [0.37464897]
 [0.01091519]
 [0.00109536]
 [0.26292005]
 [0.00743711]
 [0.0965

Output:
[[0.04499681]
 [0.37464897]
 [0.01091519]
 [0.00109536]
 [0.26292005]
 [0.00743711]
 [0.09651495]
 [0.00350992]
 [0.01114994]
 [0.00052363]]
Label 5
Answer of the NN is 1.
Output:
[[0.00753632]
 [0.00461438]
 [0.00357422]
 [0.00221661]
 [0.12989398]
 [0.00518615]
 [0.02295351]
 [0.09032299]
 [0.004426  ]
 [0.20623339]]
Label 9
Answer of the NN is 9.
Statistics of the NN:
Score: 6 of 9 correct.
Output:
[[0.43963714]
 [0.00854484]
 [0.45763481]
 [0.02109729]
 [0.00076583]
 [0.10380043]
 [0.06715647]
 [0.00459864]
 [0.02720487]
 [0.00190836]]
Label 2
Answer of the NN is 2.
Output:
[[0.00731108]
 [0.98018983]
 [0.02762158]
 [0.01459108]
 [0.0093039 ]
 [0.02486301]
 [0.01641603]
 [0.00965292]
 [0.00726756]
 [0.02505962]]
Label 1
Answer of the NN is 1.
Output:
[[0.81885463]
 [0.00664031]
 [0.01765856]
 [0.00297947]
 [0.00388589]
 [0.00546423]
 [0.05624452]
 [0.0681655 ]
 [0.00451161]
 [0.00288135]]
Label 0
Answer of the NN is 0.
Output:
[[0.01259507]
 [0.0027706 ]
 [0.03732517]
 [0.0

Output:
[[0.00203896]
 [0.01030875]
 [0.00716818]
 [0.29977511]
 [0.27293757]
 [0.00854992]
 [0.03784217]
 [0.00947253]
 [0.00522758]
 [0.01406943]]
Label 9
Answer of the NN is 3.
Output:
[[0.04499681]
 [0.37464897]
 [0.01091519]
 [0.00109536]
 [0.26292005]
 [0.00743711]
 [0.09651495]
 [0.00350992]
 [0.01114994]
 [0.00052363]]
Label 5
Answer of the NN is 1.
Output:
[[0.00753632]
 [0.00461438]
 [0.00357422]
 [0.00221661]
 [0.12989398]
 [0.00518615]
 [0.02295351]
 [0.09032299]
 [0.004426  ]
 [0.20623339]]
Label 9
Answer of the NN is 9.
Statistics of the NN:
Score: 6 of 9 correct.
Output:
[[0.43963714]
 [0.00854484]
 [0.45763481]
 [0.02109729]
 [0.00076583]
 [0.10380043]
 [0.06715647]
 [0.00459864]
 [0.02720487]
 [0.00190836]]
Label 2
Answer of the NN is 2.
Output:
[[0.00731108]
 [0.98018983]
 [0.02762158]
 [0.01459108]
 [0.0093039 ]
 [0.02486301]
 [0.01641603]
 [0.00965292]
 [0.00726756]
 [0.02505962]]
Label 1
Answer of the NN is 1.
Output:
[[0.81885463]
 [0.00664031]
 [0.01765856]
 [0.0

Output:
[[0.43963714]
 [0.00854484]
 [0.45763481]
 [0.02109729]
 [0.00076583]
 [0.10380043]
 [0.06715647]
 [0.00459864]
 [0.02720487]
 [0.00190836]]
Label 2
Answer of the NN is 2.
Output:
[[0.00731108]
 [0.98018983]
 [0.02762158]
 [0.01459108]
 [0.0093039 ]
 [0.02486301]
 [0.01641603]
 [0.00965292]
 [0.00726756]
 [0.02505962]]
Label 1
Answer of the NN is 1.
Output:
[[0.81885463]
 [0.00664031]
 [0.01765856]
 [0.00297947]
 [0.00388589]
 [0.00546423]
 [0.05624452]
 [0.0681655 ]
 [0.00451161]
 [0.00288135]]
Label 0
Answer of the NN is 0.
Output:
[[0.01259507]
 [0.0027706 ]
 [0.03732517]
 [0.00506555]
 [0.9348983 ]
 [0.00930126]
 [0.01623883]
 [0.12060654]
 [0.0186705 ]
 [0.02493413]]
Label 4
Answer of the NN is 4.
Output:
[[0.00688828]
 [0.98254642]
 [0.01787129]
 [0.01396862]
 [0.00823656]
 [0.0152356 ]
 [0.00534242]
 [0.014027  ]
 [0.00734004]
 [0.0177523 ]]
Label 1
Answer of the NN is 1.
Output:
[[0.00078025]
 [0.00244279]
 [0.00730579]
 [0.01343052]
 [0.34328002]
 [0.02831128]
 [0.0310

[[0.00753632]
 [0.00461438]
 [0.00357422]
 [0.00221661]
 [0.12989398]
 [0.00518615]
 [0.02295351]
 [0.09032299]
 [0.004426  ]
 [0.20623339]]
Label 9
Answer of the NN is 9.
Statistics of the NN:
Score: 6 of 9 correct.
Output:
[[0.43963714]
 [0.00854484]
 [0.45763481]
 [0.02109729]
 [0.00076583]
 [0.10380043]
 [0.06715647]
 [0.00459864]
 [0.02720487]
 [0.00190836]]
Label 2
Answer of the NN is 2.
Output:
[[0.00731108]
 [0.98018983]
 [0.02762158]
 [0.01459108]
 [0.0093039 ]
 [0.02486301]
 [0.01641603]
 [0.00965292]
 [0.00726756]
 [0.02505962]]
Label 1
Answer of the NN is 1.
Output:
[[0.81885463]
 [0.00664031]
 [0.01765856]
 [0.00297947]
 [0.00388589]
 [0.00546423]
 [0.05624452]
 [0.0681655 ]
 [0.00451161]
 [0.00288135]]
Label 0
Answer of the NN is 0.
Output:
[[0.01259507]
 [0.0027706 ]
 [0.03732517]
 [0.00506555]
 [0.9348983 ]
 [0.00930126]
 [0.01623883]
 [0.12060654]
 [0.0186705 ]
 [0.02493413]]
Label 4
Answer of the NN is 4.
Output:
[[0.00688828]
 [0.98254642]
 [0.01787129]
 [0.01396862]

Output:
[[0.00203896]
 [0.01030875]
 [0.00716818]
 [0.29977511]
 [0.27293757]
 [0.00854992]
 [0.03784217]
 [0.00947253]
 [0.00522758]
 [0.01406943]]
Label 9
Answer of the NN is 3.
Output:
[[0.04499681]
 [0.37464897]
 [0.01091519]
 [0.00109536]
 [0.26292005]
 [0.00743711]
 [0.09651495]
 [0.00350992]
 [0.01114994]
 [0.00052363]]
Label 5
Answer of the NN is 1.
Output:
[[0.00753632]
 [0.00461438]
 [0.00357422]
 [0.00221661]
 [0.12989398]
 [0.00518615]
 [0.02295351]
 [0.09032299]
 [0.004426  ]
 [0.20623339]]
Label 9
Answer of the NN is 9.
Statistics of the NN:
Score: 6 of 9 correct.
Output:
[[0.43963714]
 [0.00854484]
 [0.45763481]
 [0.02109729]
 [0.00076583]
 [0.10380043]
 [0.06715647]
 [0.00459864]
 [0.02720487]
 [0.00190836]]
Label 2
Answer of the NN is 2.
Output:
[[0.00731108]
 [0.98018983]
 [0.02762158]
 [0.01459108]
 [0.0093039 ]
 [0.02486301]
 [0.01641603]
 [0.00965292]
 [0.00726756]
 [0.02505962]]
Label 1
Answer of the NN is 1.
Output:
[[0.81885463]
 [0.00664031]
 [0.01765856]
 [0.0

Output:
[[0.01259507]
 [0.0027706 ]
 [0.03732517]
 [0.00506555]
 [0.9348983 ]
 [0.00930126]
 [0.01623883]
 [0.12060654]
 [0.0186705 ]
 [0.02493413]]
Label 4
Answer of the NN is 4.
Output:
[[0.00688828]
 [0.98254642]
 [0.01787129]
 [0.01396862]
 [0.00823656]
 [0.0152356 ]
 [0.00534242]
 [0.014027  ]
 [0.00734004]
 [0.0177523 ]]
Label 1
Answer of the NN is 1.
Output:
[[0.00078025]
 [0.00244279]
 [0.00730579]
 [0.01343052]
 [0.34328002]
 [0.02831128]
 [0.03101971]
 [0.02936238]
 [0.02496415]
 [0.72077414]]
Label 4
Answer of the NN is 9.
Output:
[[0.00203896]
 [0.01030875]
 [0.00716818]
 [0.29977511]
 [0.27293757]
 [0.00854992]
 [0.03784217]
 [0.00947253]
 [0.00522758]
 [0.01406943]]
Label 9
Answer of the NN is 3.
Output:
[[0.04499681]
 [0.37464897]
 [0.01091519]
 [0.00109536]
 [0.26292005]
 [0.00743711]
 [0.09651495]
 [0.00350992]
 [0.01114994]
 [0.00052363]]
Label 5
Answer of the NN is 1.
Output:
[[0.00753632]
 [0.00461438]
 [0.00357422]
 [0.00221661]
 [0.12989398]
 [0.00518615]
 [0.0229

Output:
[[0.00078025]
 [0.00244279]
 [0.00730579]
 [0.01343052]
 [0.34328002]
 [0.02831128]
 [0.03101971]
 [0.02936238]
 [0.02496415]
 [0.72077414]]
Label 4
Answer of the NN is 9.
Output:
[[0.00203896]
 [0.01030875]
 [0.00716818]
 [0.29977511]
 [0.27293757]
 [0.00854992]
 [0.03784217]
 [0.00947253]
 [0.00522758]
 [0.01406943]]
Label 9
Answer of the NN is 3.
Output:
[[0.04499681]
 [0.37464897]
 [0.01091519]
 [0.00109536]
 [0.26292005]
 [0.00743711]
 [0.09651495]
 [0.00350992]
 [0.01114994]
 [0.00052363]]
Label 5
Answer of the NN is 1.
Output:
[[0.00753632]
 [0.00461438]
 [0.00357422]
 [0.00221661]
 [0.12989398]
 [0.00518615]
 [0.02295351]
 [0.09032299]
 [0.004426  ]
 [0.20623339]]
Label 9
Answer of the NN is 9.
Statistics of the NN:
Score: 6 of 9 correct.
Output:
[[0.43963714]
 [0.00854484]
 [0.45763481]
 [0.02109729]
 [0.00076583]
 [0.10380043]
 [0.06715647]
 [0.00459864]
 [0.02720487]
 [0.00190836]]
Label 2
Answer of the NN is 2.
Output:
[[0.00731108]
 [0.98018983]
 [0.02762158]
 [0.0

Output:
[[0.00731108]
 [0.98018983]
 [0.02762158]
 [0.01459108]
 [0.0093039 ]
 [0.02486301]
 [0.01641603]
 [0.00965292]
 [0.00726756]
 [0.02505962]]
Label 1
Answer of the NN is 1.
Output:
[[0.81885463]
 [0.00664031]
 [0.01765856]
 [0.00297947]
 [0.00388589]
 [0.00546423]
 [0.05624452]
 [0.0681655 ]
 [0.00451161]
 [0.00288135]]
Label 0
Answer of the NN is 0.
Output:
[[0.01259507]
 [0.0027706 ]
 [0.03732517]
 [0.00506555]
 [0.9348983 ]
 [0.00930126]
 [0.01623883]
 [0.12060654]
 [0.0186705 ]
 [0.02493413]]
Label 4
Answer of the NN is 4.
Output:
[[0.00688828]
 [0.98254642]
 [0.01787129]
 [0.01396862]
 [0.00823656]
 [0.0152356 ]
 [0.00534242]
 [0.014027  ]
 [0.00734004]
 [0.0177523 ]]
Label 1
Answer of the NN is 1.
Output:
[[0.00078025]
 [0.00244279]
 [0.00730579]
 [0.01343052]
 [0.34328002]
 [0.02831128]
 [0.03101971]
 [0.02936238]
 [0.02496415]
 [0.72077414]]
Label 4
Answer of the NN is 9.
Output:
[[0.00203896]
 [0.01030875]
 [0.00716818]
 [0.29977511]
 [0.27293757]
 [0.00854992]
 [0.0378